### ISSUE TITLE
Invalid export preset name

### ISSUE THREAD

**Issue by oeN** [josephbmanley/build-godot-action#12]
Hi,
I have some problem on getting this action works, I have 2 presets configured into `export_presets.cfg`, I wanto to use the second one, named "linux":

```
[preset.1]

name="linux"
platform="Linux/X11"
runnable=true
custom_features=""
export_filter="all_resources"
include_filter=""
exclude_filter=""
export_path="../exports/project_name"
patch_list=PoolStringArray(  )
script_export_mode=1
script_encryption_key=""

[preset.1.options]

texture_format/bptc=false
texture_format/s3tc=true
texture_format/etc=false
texture_format/etc2=false
texture_format/no_bptc_fallbacks=true
binary_format/64_bits=true
binary_format/embed_pck=false
custom_template/release=""
custom_template/debug=""
```

but I keep getting the error:

```
ERROR: _fs_changed: Invalid export preset name: linux.
   At: editor/editor_node.cpp:634.
```

the workflow file is the following one:

```
# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v1

    - name: Build Godot
      uses: josephbmanley/build-godot-action@v1.3.4
      with:
        name: prject_name
        preset: linux
        debugMode: false
```
I've also tried the `v2` for the checkout step but nothing changed.

can you help me?
thanks!
