### ISSUE TITLE
Invalid export preset name

### ISSUE THREAD

**Issue by Hapique** [josephbmanley/build-godot-action#14]
I saw that there is another issue with the same name, it's not working for me and I don't understand why.

I get the following error while running the Action: `_fs_changed: Invalid export preset name: linux. Make sure `export_presets.cfg` is present in the current directory.`

The `export_presets.cfg` is at the root of my project (same for `project.godot`).

I have the following config:

```cfg
[preset.0]

name="mac"
platform="Mac OSX"
runnable=true
custom_features=""
export_filter="all_resources"
include_filter=""
exclude_filter=""
export_path="build/Game Design.dmg"
patch_list=PoolStringArray(  )
script_export_mode=1
script_encryption_key=""

[preset.0.options]

custom_template/debug=""
custom_template/release=""
application/name=""
application/info="Made with Godot Engine"
application/icon=""
application/identifier=""
application/signature=""
application/short_version="1.0"
application/version="1.0"
application/copyright=""
display/high_res=false
privacy/camera_usage_description=""
privacy/microphone_usage_description=""
codesign/enable=false
codesign/identity=""
codesign/timestamp=true
codesign/hardened_runtime=true
codesign/entitlements=""
codesign/custom_options=PoolStringArray(  )
texture_format/s3tc=true
texture_format/etc=false
texture_format/etc2=false

[preset.1]

name="windows"
platform="Windows Desktop"
runnable=true
custom_features=""
export_filter="all_resources"
include_filter=""
exclude_filter=""
export_path="build/Game Design.exe"
patch_list=PoolStringArray(  )
script_export_mode=1
script_encryption_key=""

[preset.1.options]

texture_format/bptc=false
texture_format/s3tc=true
texture_format/etc=false
texture_format/etc2=false
texture_format/no_bptc_fallbacks=true
binary_format/64_bits=true
binary_format/embed_pck=false
custom_template/release=""
custom_template/debug=""
codesign/enable=false
codesign/identity=""
codesign/password=""
codesign/timestamp=true
codesign/timestamp_server_url=""
codesign/digest_algorithm=1
codesign/description=""
codesign/custom_options=PoolStringArray(  )
application/icon=""
application/file_version=""
application/product_version=""
application/company_name=""
application/product_name=""
application/file_description=""
application/copyright=""
application/trademarks=""

[preset.2]

name="linux"
platform="Linux/X11"
runnable=true
custom_features=""
export_filter="all_resources"
include_filter=""
exclude_filter=""
export_path="build/Game Design.x86_64"
patch_list=PoolStringArray(  )
script_export_mode=1
script_encryption_key=""

[preset.2.options]

texture_format/bptc=false
texture_format/s3tc=true
texture_format/etc=false
texture_format/etc2=false
texture_format/no_bptc_fallbacks=true
binary_format/64_bits=true
binary_format/embed_pck=false
custom_template/release=""
custom_template/debug=""
```

```yml
name: Build Godot Project

on:
  push: {}
  pull_request: {}

jobs:
  Godot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Build
        id: build
        uses: josephbmanley/build-godot-action@v1.4.0
        with:
          name: Game Design
          preset: linux
          debugMode: "true"
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Client - Linux
          path: ${{ github.workspace }}/${{ steps.build.outputs.build }}
```

Thanks in advance for the help!
