### ISSUE TITLE
Fails to build

### ISSUE THREAD

**Issue by Jatoxo** [josephbmanley/build-godot-action#15]
```
ERROR: _fs_changed: Invalid export preset name: windows. Make sure `export_presets.cfg` is present in the current directory.
   At: editor/editor_node.cpp:753
```
This error appears for linux, mac, and windows

The export presets are as they should be, and are in the the same directory as project.godot

[export_presets.zip](https://github.com/josephbmanley/build-godot-action/files/6089817/export_presets.zip)

The job, yml is located at the default location

```
jobs:
  Godot:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [windows, linux, mac]
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Build
        id: build
        uses: josephbmanley/build-godot-action@v1.4.0
        with:
          name: StructureMaker
          preset: ${{ matrix.platform }}
          debugMode: "false"
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Client - ${{ matrix.platform }}
          path: ${{ github.workspace }}/${{ steps.build.outputs.build }}

```
