### ISSUE TITLE
Filetypes gone after building

### ISSUE THREAD

**Issue by lreinink** [josephbmanley/build-godot-action#16]
Hello, when I'm building the project on my machine it works for Windows and Mac, but when using your tool, the filetypes are gone. For Windows, I can just add .exe behind it, and it works, but for Mac, adding .app behind it does not work. Am I doing something wrong here?

**Comment by kb173** [comment]
We've run into this as well and after some testing, it seems like it is because this Action invokes the command like this:

`godot --export "platform" name`

The `name` specifies the filename of the exported file, and it comes from what's written in your Action yml, e.g.:

```
        with:
          name: my-game
```

In this case, it'd run `godot --export "platform" my-game`, and this `my-game` overrides the name from the export preset which presumably has the correct ending.

[The Godot docs sound like the ending should be appended automatically when exporting like this](https://docs.godotengine.org/en/stable/getting_started/workflow/export/exporting_projects.html#exporting-from-the-command-line), so maybe that's where this issue comes from. [Elsewhere in the docs, however, the ending is included in this name parameter](https://docs.godotengine.org/en/stable/getting_started/editor/command_line_tutorial.html#setting-the-project-path).

Either way, it might be helpful to add an option which does not include any name override and just uses the name configured in the preset.

**Comment by semirix** [comment]
This is easily fixed by adding some extra fields in the matrix. Here's an example config:
```yaml
name: Build Godot

on:
  push: {}
  pull_request: {}

jobs:
  Godot:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
        - name: Windows
          file: game.exe
        - name: MacOS
          file: game.zip
        - name: Linux
          file: game
    steps:
      - uses: actions/checkout@v2
      - name: Build
        id: build
        uses: manleydev/build-godot-action@v1.4.1
        with:
          name: ${{ matrix.platform.file }}
          preset: ${{ matrix.platform.name }}
          debugMode: false
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Game - ${{ matrix.platform.name }}
          path: ${{ github.workspace }}/${{ steps.build.outputs.build }}
```
**Edit:** Fixed MacOS file extension for anyone googling for a solution.
