### ISSUE TITLE
export_presets.cfg not found

### ISSUE THREAD

**Issue by QuentinWidlocher** [josephbmanley/build-godot-action#18]
Hi, thanks for you action.

When I try to build my project, it doesn't find `export_presets.cfg` and I don't really know why.

I know there are some issues here with the same problem, but I'm using `v1.4.1` (same with `master`).

<details open>
<summary>The error</summary>

```
ERROR: _fs_changed: Invalid export preset name: linux. Make sure `export_presets.cfg` is present in the current directory.
   At: editor/editor_node.cpp:770.
```
</details>

<details>
<summary>YML file</summary>

  ```yml
  name: Build
  on:
      push:
          branches:
              - main
      pull_request:
          types: [opened, synchronize, reopened]
  jobs:
      builds:
          name: Builds
          runs-on: ubuntu-latest
          strategy:
            matrix:
              platform: [ linux, windows ]
          steps:
              - name: Build for ${{ matrix.platform }}
                id: build
                uses: josephbmanley/build-godot-action@v1.4.1
                with:
                    name: GoGodotJam2021
                    preset: ${{ matrix.platform }}
              - name: Upload ${{ matrix.platform }} artifact
                uses: actions/upload-artifact@v2
                with:
                  name: ${{ matrix.platform }} build
                  path: ${{ github.workspace }}/${{ steps.build.outputs.build }}
  ```
</details>

<details>
  <summary>export_presets.cfg located at the root of my project :</summary>

  ```ini
[preset.0]

name="windows"
platform="Windows Desktop"
runnable=true
custom_features=""
export_filter="all_resources"
include_filter=""
exclude_filter=""
export_path="Builds/Windows/GoGodotJam2021.exe"
script_export_mode=1
script_encryption_key=""

[preset.0.options]

custom_template/debug=""
custom_template/release=""
binary_format/64_bits=true
binary_format/embed_pck=false
texture_format/bptc=false
texture_format/s3tc=true
texture_format/etc=false
texture_format/etc2=false
texture_format/no_bptc_fallbacks=true
codesign/enable=false
codesign/identity=""
codesign/password=""
codesign/timestamp=true
codesign/timestamp_server_url=""
codesign/digest_algorithm=1
codesign/description=""
codesign/custom_options=PoolStringArray(  )
application/icon=""
application/file_version=""
application/product_version=""
application/company_name="Kale and Lazard"
application/product_name="GoGodotJam2021"
application/file_description=""
application/copyright=""
application/trademarks=""

[preset.1]

name="linux"
platform="Linux/X11"
runnable=true
custom_features=""
export_filter="all_resources"
include_filter=""
exclude_filter=""
export_path="Builds/Linux/GoGodotJam2021.exe.x86_64"
script_export_mode=1
script_encryption_key=""

[preset.1.options]

custom_template/debug=""
custom_template/release=""
binary_format/64_bits=true
binary_format/embed_pck=false
texture_format/bptc=false
texture_format/s3tc=true
texture_format/etc=false
texture_format/etc2=false
texture_format/no_bptc_fallbacks=true
```
</details>

[Here is the entire repo](https://github.com/QuentinWidlocher/GoGodotJam2021)
