### ISSUE TITLE
Godot Build for mac failed silently

### ISSUE THREAD

**Issue by Exifs** [josephbmanley/build-godot-action#25]
Hey There ! 

I encounter a silent build failure for macOS only.

<img width="1639" alt="image" src="https://github.com/yeslayla/build-godot-action/assets/5650537/c6143712-0799-47a6-8a73-c46bc099d17b">

Any clues ?

ofc the export is working on a macbook.

**Comment by asciifaceman** [comment]
Mac builds seem broken right now for me as well . I can produce mac builds locally, might be an issue with xplatform builds from ubuntu

**Comment by tjlaxs** [comment]
I get a very similar thing but with minor differences:
![image](https://github.com/yeslayla/build-godot-action/assets/3730759/729e6aa7-33fa-41e1-80f7-323e62ed8fcc)
And this results with empty build-folder:
![image](https://github.com/yeslayla/build-godot-action/assets/3730759/8a6c47cb-e9b6-40b6-8527-234220f660de)

Tried to drop the Dockerfile base image version to older but didn't seem to help.

The export fails for something like path_p missing from export. This might be different problem and just a configuration issue. But the errors are similar and the build resulting to Success is pretty annoying.

**Comment by tjlaxs** [comment]
Found out the problem in my case was that you can only build Godot project on linux with ".zip" ending, so when the name parameter for the action is changed to "example.zip" it works fine and builds the unnotarized unsigned executable that is blocked in Gatekeeper but works fine.

**Comment by tjlaxs** [comment]
By the screenshot I would guess you are running also the linux docker image and I'm guessing you use ".dmg" or something like that as the error is complaining Xcode missing which you only get with Apple machines probably. So I would guess that to get the real images you need a build pipeline to be run on Apple machines.

**Comment by l0u1sg** [comment]
I have the same issue right now. Here's my yml workflow file :
```yml
jobs:
  Godot:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - name: Windows
            file: game.exe
          - name: MacOS
            file: game.zip
          - name: Linux
            file: game.zip
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Build
        id: build
        uses: manleydev/build-godot-action@v1.5.0
        with:
          name: ${{ matrix.platform.file }}
          preset: ${{ matrix.platform.name }}
          debugMode: "true"
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Client - ${{ matrix.platform.name }}
          path: ${{ github.workspace }}/${{ steps.build.outputs.build }}
```

Like you say @tjlaxs I put a zip extension for MacOS and Linux. But it seems that the main error is that Xcode command line tools are missing
![CleanShot 2023-11-16 at 15 01 03@2x](https://github.com/yeslayla/build-godot-action/assets/46707587/452b0e62-8ccd-438e-b9b3-7c03edfb2d4b)
